# 1. 使用 rocker 镜像
FROM rocker/rstudio:4

# 2. 设置环境变量，供 rocker 脚本和系统使用
ENV DEFAULT_USER=jz

# 3. 执行用户创建脚本 (以 root 身份)
RUN <<EOF
if grep -q "1000" /etc/passwd; then
    userdel --remove "$(id -un 1000)";
fi
/rocker_scripts/default_user.sh
EOF
